# Automatically generated by configure - do not modify
TARGET_NAME=riscv32
target=riscv32-softmmu
CONFIG_SOFTMMU=y
QEMU=/Users/alastair/Desktop/Code/ferment/pkgmanager/Installed/qemu/build/qemu-system-riscv32
CROSS_CC_GUEST_CFLAGS=
