# Automatically generated by configure - do not modify
TARGET_NAME=ppc
target=ppc-softmmu
CONFIG_SOFTMMU=y
QEMU=/Users/alastair/Desktop/Code/ferment/pkgmanager/Installed/qemu/build/qemu-system-ppc
CROSS_CC_GUEST_CFLAGS=-m32
