# Automatically generated by configure - do not modify
TARGET_NAME=alpha
target=alpha-softmmu
CONFIG_SOFTMMU=y
QEMU=/Users/alastair/Desktop/Code/ferment/pkgmanager/Installed/qemu/build/qemu-system-alpha
CROSS_CC_GUEST_CFLAGS=
