# Automatically generated by configure - do not modify
TARGET_NAME=nios2
target=nios2-softmmu
CONFIG_SOFTMMU=y
QEMU=/Users/alastair/Desktop/Code/ferment/pkgmanager/Installed/qemu/build/qemu-system-nios2
CROSS_CC_GUEST_CFLAGS=
