# Automatically generated by configure - do not modify
TARGET_NAME=mips
target=mips-softmmu
CONFIG_SOFTMMU=y
QEMU=/Users/alastair/Desktop/Code/ferment/pkgmanager/Installed/qemu/build/qemu-system-mips
CROSS_CC_GUEST_CFLAGS=
