# Automatically generated by configure - do not modify
TARGET_NAME=sh4
target=sh4-softmmu
CONFIG_SOFTMMU=y
QEMU=/Users/alastair/Desktop/Code/ferment/pkgmanager/Installed/qemu/build/qemu-system-sh4
CROSS_CC_GUEST_CFLAGS=
