# Automatically generated by configure - do not modify
TARGET_NAME=i386
target=i386-softmmu
CONFIG_SOFTMMU=y
QEMU=/Users/alastair/Desktop/Code/ferment/pkgmanager/Installed/qemu/build/qemu-system-i386
CROSS_CC_GUEST_CFLAGS=-m32
