# Automatically generated by configure - do not modify
TARGET_NAME=sparc
target=sparc-softmmu
CONFIG_SOFTMMU=y
QEMU=/Users/alastair/Desktop/Code/ferment/pkgmanager/Installed/qemu/build/qemu-system-sparc
CROSS_CC_GUEST_CFLAGS=-m32 -mv8plus -mcpu=ultrasparc
