# Automatically generated by configure - do not modify
TARGET_NAME=microblaze
target=microblaze-softmmu
CONFIG_SOFTMMU=y
QEMU=/Users/alastair/Desktop/Code/ferment/pkgmanager/Installed/qemu/build/qemu-system-microblaze
CROSS_CC_GUEST_CFLAGS=
