# Automatically generated by configure - do not modify
TARGET_NAME=mips64el
target=mips64el-softmmu
CONFIG_SOFTMMU=y
QEMU=/Users/alastair/Desktop/Code/ferment/pkgmanager/Installed/qemu/build/qemu-system-mips64el
CROSS_CC_GUEST_CFLAGS=
