# Automatically generated by configure - do not modify
TARGET_NAME=arm
target=arm-softmmu
CONFIG_SOFTMMU=y
QEMU=/Users/alastair/Desktop/Code/ferment/pkgmanager/Installed/qemu/build/qemu-system-arm
CROSS_CC_GUEST_CFLAGS=
